name: Invariance tests

inputs:
  artifact-name:
    description: 'Name of the uploaded artifact'
    required: false
    default: 'invariance-test-results'

runs:
  using: "composite"
  steps:
    - name: Show gcc version
      run: |
        gcc --version
      shell: bash

    - name: Show ldd version
      run: |
        ldd --version || true
      shell: bash

    - name: Run invariance tests
      run: python -m INCHI-1-TEST.run_invariance_tests ci
      shell: bash

    - name: Write invariance summary
      if: '!cancelled()'
      run: python -m INCHI-1-TEST.parse_invariance_log ci
      shell: bash

    - name: Upload invariance test results
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ./INCHI-1-TEST/data/ci/*_invariance_test.log
          ./INCHI-1-TEST/data/ci/*_invariance_test_*.html
