name: Compile InChI library from triggering branch

runs:
  using: "composite"
  steps:
    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE" # https://github.com/actions/runner-images/issues/6775
        mkdir "$GITHUB_WORKSPACE/$LIB_DIR"
        ./INCHI-1-TEST/compile_inchi_lib.sh $BRANCH "$GITHUB_WORKSPACE/$LIB_DIR"
        if [ "$BRANCH" != "main" ]; then
          # Rename library to libinchi.so.main, since that's the name the tests expect.
          mv "$GITHUB_WORKSPACE/$LIB_DIR/libinchi.so.$BRANCH" "$GITHUB_WORKSPACE/$LIB_DIR/libinchi.so.main"
        fi
      shell: bash
      env:
        BRANCH: ${{ github.ref_name }}
        LIB_DIR: INCHI-1-TEST/libs
